export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const LOAD_PERSON_INFO = 'LOAD_PERSON_INFO';

export const DATA_FETCH_PROTECTED_DATA_REQUEST = 'DATA_FETCH_PROTECTED_DATA_REQUEST';
export const DATA_RECEIVE_PROTECTED_DATA = 'DATA_RECEIVE_PROTECTED_DATA';

export const LOAD_PUBLIC_MEMOS_SUCCESS= 'LOAD_PUBLIC_MEMOS_SUCCESS';
export const LOAD_PUBLIC_MEMO_SUCCESS= 'LOAD_PUBLIC_MEMO_SUCCESS';
export const LOAD_PRIVATE_MEMOS_SUCCESS = 'LOAD_PRIVATE_MEMOS_SUCCESS';
export const LOAD_PRIVATE_MEMO_SUCCESS = 'LOAD_PRIVATE_MEMO_SUCCESS';

export const UPDATE_PUBLIC_MEMO_SUCCESS='UPDATE_PUBLIC_MEMO_SUCCESS';

export const SET_USER ='SET_USER';
export const SET_TITLE = 'SET_TITLE';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
