export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const LOAD_PERSON_INFO = 'LOAD_PERSON_INFO';

export const DATA_FETCH_PROTECTED_DATA_REQUEST = 'DATA_FETCH_PROTECTED_DATA_REQUEST';
export const DATA_RECEIVE_PROTECTED_DATA = 'DATA_RECEIVE_PROTECTED_DATA';

export const LOAD_PUBLIC_MEMOS_SUCCESS= 'LOAD_PUBLIC_MEMOS_SUCCESS';
export const LOAD_PUBLIC_MEMO_SUCCESS= 'LOAD_PUBLIC_MEMO_SUCCESS';
export const LOAD_PRIVATE_MEMOS_SUCCESS = 'LOAD_PRIVATE_MEMOS_SUCCESS';
export const LOAD_PRIVATE_MEMO_SUCCESS = 'LOAD_PRIVATE_MEMO_SUCCESS';

export const LOAD_ASSIGNMENT_SUCCESS = 'LOAD_ASSIGNMENT_SUCCESS';
export const LOAD_ASSIGNMENT_SUBMISSIONS_SUCCESS = 'LOAD_ASSIGNMENT_SUBMISSIONS_SUCCESS';
export const LOAD_ASSIGNMENT_REVIEWS_SUCCESS = 'LOAD_ASSIGNMENT_REVIEWS_SUCCESS';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT_SUCCESS = 'UPDATE_ASSIGNMENT_SUCCESS';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const LOAD_SUBJECTS_SUCCESS = "LOAD_SUBJECTS_SUCCESS";
export const LOAD_SUBJECT_KNOWLEDGE_SUCCESS = "LOAD_SUBJECT_KNOWLEDGE_SUCCESS";

// medias app
export const LOAD_VIDEOS_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const LOAD_VIDEO_SUCCESS = 'LOAD_VIDEO_SUCCESS';
export const UPDATE_VIDEOS_PAGE_NUMBER = 'UPDATE_VIDEOS_PAGE_NUMBER';
export const LOAD_USER_PLAY_RECORD_SET_SUCCESS = 'LOAD_USER_PLAY_RECORD_SET_SUCCESS';
